### ISSUE TITLE
Preparar ambiente JHipster

### ISSUE THREAD

**Issue by cemarciano** [carloseduardov8/Viajato#2]
Familiarizar-se com o ambiente JHipster e torná-lo pronto para criação do projeto.

**Comment by lucasbarcellosoliveira** [comment]
https://stackoverflow.com/questions/52504574/yarn-npm-for-jhipster

**Comment by lucasbarcellosoliveira** [comment]
https://github.com/gdi2290/angular-starter/issues/1997

**Comment by lucasbarcellosoliveira** [comment]
https://stackoverflow.com/questions/29492240/error-cannot-find-module-webpack

**Comment by lucasbarcellosoliveira** [comment]
http://roufid.com/no-compiler-is-provided-in-this-environment/
